"""Generate the frontend schema types from the backend OpenAPI contract."""

import argparse
import importlib
import json
import re
from pathlib import Path


def name(value: str) -> str:
    return re.sub(r"[^A-Za-z0-9_]", "_", value)


def ts(schema: dict) -> str:
    if "$ref" in schema:
        return name(schema["$ref"].rsplit("/", 1)[1])
    if "const" in schema:
        return json.dumps(schema["const"])
    if "enum" in schema:
        return " | ".join(json.dumps(x) for x in schema["enum"])
    if "anyOf" in schema:
        return " | ".join(ts(x) for x in schema["anyOf"])
    kind = schema.get("type")
    if kind == "array":
        return f"Array<{ts(schema.get('items', {}))}>"
    if kind == "object" or "properties" in schema:
        props = schema.get("properties", {})
        if not props:
            additional = schema.get("additionalProperties")
            return (
                "Record<string, "
                + (ts(additional) if isinstance(additional, dict) else "unknown")
                + ">"
            )
        required = schema.get("required", [])
        return (
            "{\n"
            + "\n".join(
                f"  {json.dumps(key)}{'' if key in required else '?'}: {ts(value)};"
                for key, value in props.items()
            )
            + "\n}"
        )
    return {
        "string": "string",
        "integer": "number",
        "number": "number",
        "boolean": "boolean",
        "null": "null",
    }.get(kind, "unknown")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--app", choices=["app.vendor_app", "app.main"], default="app.main")
    args = parser.parse_args()
    schema = importlib.import_module(args.app).create_app().openapi()
    target = Path("../bnh-ui/src/lib/api")
    target.mkdir(parents=True, exist_ok=True)
    (target / "openapi.json").write_text(json.dumps(schema, indent=2) + "\n")
    declarations = ["// Generated by bnh-backend/scripts/export_openapi.py. Do not edit."]
    declarations.extend(
        f"export type {name(key)} = {ts(value)};"
        for key, value in schema["components"]["schemas"].items()
    )
    (target / "schema.ts").write_text("\n\n".join(declarations) + "\n")
    print("Exported OpenAPI and generated frontend schema types.")


if __name__ == "__main__":
    main()
